### ISSUE TITLE
Twitter Trend Tracker

### ISSUE THREAD

**Issue by imjakedaniels** [imjakedaniels/TidyTuesday#1]
**WHAT IS IT?**
A service that let's the end user get notified for trends that contain some of the terms they define.

**WHY AM I DOING IT?**
To build a product: an database, an API, a GUI,

**WHEN IS IT DONE?**
When a client can add inputs and get notified via email if a trend is triggered.

**TASKS**
- [ ] Write my data into a database
- [ ] Connect to the database using functions
- [ ] Create Shiny App
  - [ ] What's trending now
  - [ ] User Trends
  - [ ] Keyword lookup
  - [ ] User input: keywords + email
- [ ] Write user keywords and email into database
- [ ] Email users about trends

**FUTURE NOTES**
- API and database https://www.granvillematheson.com/post/creating-an-api-for-big-text-data-with-rsqlite-dbplyr-and-plumber/
- Manually label trends and do a multi-label regression to predict what a trend is about
