### ISSUE TITLE
Twitter Trend Non-profit

### ISSUE THREAD

**Issue by imjakedaniels** [imjakedaniels/TidyTuesday#2]
**WHAT IS IT?**
A group of accounts tweeting wordclouds and chatter charts about various topics ie. Politics, Sexual Assault, Police, Environmental detected in the news yesterday.

**WHY AM I DOING IT?**
To build a non-profit that tracks key issues.

**WHEN IS IT DONE?**
When 1 MVP account is complete (LGBQT+, Black Lives)

**TASKS**
- [ ] Select keyword groupings
- [ ] Create a twitter account & app
- [ ] Build ETL that will post when a certain number of keywords are in a trend
- [ ] Post treemap of all qualified trends
- [ ] Post wordcloud/chatter charts of top 3/5
- [ ] Quote tweet top tweets in the comments
- [ ] Build script to auto-follow people

**FUTURE NOTES**
- One main account that retweets all things
- Expand social media outlets with Hootsuite API
