### ISSUE TITLE
Cliff Proof of Concept

### ISSUE THREAD

**Issue by imjakedaniels** [imjakedaniels/TidyTuesday#3]
**WHAT IS IT?**
Could be a research project VoxPopLabs could use as recurring content. Or maybe my concept of American trend navigation, but for Canada? People can better pay attention to what's happening digitally about discussions on social issues?

**WHY AM I DOING IT?**
Pitch to Cliff for a job/grant? Iunno. Something.

**WHEN IS IT DONE?**
When #2 is complete.

**TASKS**
- [x] Familiarize with https://twitter.com/VoxPopLabs
- [ ] Gather comparables (Town Hall Index, @layoffbot)
- [x] Brainstorm

- Index of Canadian Trends about Political Parties (Use Democrats/Republicans keywords in America, Liberal, NDP, PCP)

- Index of social issue discussions in Canada and mark the trends that spike them.

- [x] Get a sample of data (two-weeks)
- [ ] Simplify the BLM app into a daily outlook of yesterday's trends (TreeMap)
- [ ] Index of many social issue discussions in America and mark any spikes with hover information (time-series)
- [ ] Each social issue keywords have a historical volume index (histogram)
- [ ] Make a weekly glimpse of related trends (Hall of Fame style)
- [ ] Make an animated wordcloud for specific trends
- [ ] Make a chatter chart

**FUTURE NOTES**
- "Social enterprise working to advance democratic participation with innovative digital products and public opinion research services."
